import { StyleSheet } from "@react-pdf/renderer";

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: "Inter",
    fontSize: 10,
    paddingTop: 40,
    paddingBottom: 60,
    paddingHorizontal: 40,
    color: "#0f172a",
  },
  h1: { fontSize: 18, fontWeight: "bold", textAlign: "center", marginBottom: 16 },
  h2: { fontSize: 11, fontWeight: "bold", marginBottom: 4, color: "#334155" },
  row: { flexDirection: "row", justifyContent: "space-between" },
  col: { flexDirection: "column" },
  spacer8: { height: 8 },
  spacer16: { height: 16 },
  senderName: { fontSize: 13, fontWeight: "bold" },
  muted: { color: "#475569" },
  meta: { alignItems: "flex-end" },
  metaLabel: { color: "#64748b" },
  metaValue: { fontWeight: "medium" },
  hr: { borderBottomWidth: 0.5, borderBottomColor: "#e2e8f0", marginVertical: 8 },
  blockTitle: { fontSize: 10, color: "#64748b", textTransform: "uppercase", marginBottom: 4 },
  table: { marginTop: 8 },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#0f172a",
    paddingBottom: 4,
    fontWeight: "bold",
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 0.25,
    borderBottomColor: "#e2e8f0",
    paddingVertical: 4,
  },
  colIndex: { width: "5%" },
  colDesc: { width: "40%" },
  colHsn: { width: "15%" },
  colQty: { width: "10%", textAlign: "right" },
  colRate: { width: "15%", textAlign: "right" },
  colAmount: { width: "15%", textAlign: "right" },
  totalsBlock: { marginTop: 12, alignItems: "flex-end" },
  totalsRow: { flexDirection: "row", justifyContent: "flex-end", width: "50%", marginBottom: 2 },
  totalsLabel: { width: "60%", textAlign: "right", paddingRight: 8, color: "#475569" },
  totalsValue: { width: "40%", textAlign: "right" },
  grandTotal: { fontWeight: "bold", borderTopWidth: 0.5, borderTopColor: "#0f172a", paddingTop: 4 },
  words: { marginTop: 12, fontStyle: "italic", color: "#334155" },
  notes: { marginTop: 16 },
  notesTitle: { fontSize: 10, color: "#64748b", marginBottom: 2 },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    fontSize: 9,
    color: "#64748b",
    flexDirection: "row",
    justifyContent: "space-between",
  },
});
